### ISSUE TITLE
DDP comparability

### ISSUE THREAD

**Issue by LeeDoYup** [snuspl/nimble#1]
Hello. First of all, thank you for the awesome project !
Is this framework comparable with DDP (DistributedDataParallel) ?
Or is there any result that is conducted in DDP environment ?

**Comment by bgchun** [comment]
Thank you for the question!
Although our group has expertise in distributed training, in this work we focused on improving the performance of PyTorch running in a single GPU. 
I think that there's no problem of using Nimble with DDP, but we haven't done any DDP experiments yet. It'd be interesting to see the impact of Nimble on DDP training performance.

**Comment by LeeDoYup** [comment]
Thank you for the fast reply.
I will reopen if I try to use Nimble in DDP setting, and there is any update.

Again, thank you for the awesome project !
